# MySQL Database Profile (Activate with --spring.profiles.active=mysql)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://sql12.freesqldatabase.com:3306/sql12836647?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sql12836647}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:P4JJ8DGIJk}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
